// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowTennis.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TennisFeature : object, Xunit.IClassFixture<TennisFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Tennis.feature"
#line hidden
        
        public TennisFeature(TennisFeature.FixtureData fixtureData, SpecFlowTennis_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Tennis", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Le joueur A marque un point")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Le joueur A marque un point")]
        [Xunit.TraitAttribute("Category", "tennis")]
        public virtual void LeJoueurAMarqueUnPoint()
        {
            string[] tagsOfScenario = new string[] {
                    "tennis"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Le joueur A marque un point", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
    testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 7
    testRunner.Given("Le set est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    testRunner.When("Joueur A marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table1.AddRow(new string[] {
                            "A",
                            "15",
                            "0",
                            "0",
                            "0"});
                table1.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 10
    testRunner.Then("le score devrait être :", ((string)(null)), table1, "Then ");
#line hidden
#line 14
    testRunner.And("Le jeu devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Le joueur A remporte un jeu")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Le joueur A remporte un jeu")]
        public virtual void LeJoueurARemporteUnJeu()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Le joueur A remporte un jeu", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 17
    testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 18
    testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
    testRunner.Given("Le set est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
    testRunner.And("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table2.AddRow(new string[] {
                            "A",
                            "40",
                            "0",
                            "0",
                            "0"});
                table2.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 21
    testRunner.And("Le score est de :", ((string)(null)), table2, "And ");
#line hidden
#line 25
    testRunner.When("Joueur A marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
    testRunner.Then("Le jeu devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table3.AddRow(new string[] {
                            "A",
                            "0",
                            "1",
                            "0",
                            "0"});
                table3.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 27
    testRunner.And("le score devrait être :", ((string)(null)), table3, "And ");
#line hidden
#line 31
    testRunner.And("Le set devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
    testRunner.And("le resultat du jeu devrait être \"Le Joueur A mène 1 jeu à 0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Le joueur A remporte un set")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Le joueur A remporte un set")]
        public virtual void LeJoueurARemporteUnSet()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Le joueur A remporte un set", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 35
    testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 36
    testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
    testRunner.Given("Le set est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 38
    testRunner.And("Le set en cours est le set 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
    testRunner.Then("Le set en cours devrait être le set 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
    testRunner.Given("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table4.AddRow(new string[] {
                            "A",
                            "40",
                            "5",
                            "0",
                            "0"});
                table4.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 41
    testRunner.And("Le score est de :", ((string)(null)), table4, "And ");
#line hidden
#line 45
    testRunner.When("Joueur A marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
    testRunner.Then("Le jeu devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table5.AddRow(new string[] {
                            "A",
                            "0",
                            "6",
                            "0",
                            "0"});
                table5.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 47
    testRunner.And("le score devrait être :", ((string)(null)), table5, "And ");
#line hidden
#line 51
    testRunner.And("Le set devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
    testRunner.And("Le set en cours devrait être le set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
    testRunner.And("le resultat du set devrait être \"Le Joueur A remporte le set 6 jeux à 0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Le joueur A remporte le match")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Le joueur A remporte le match")]
        public virtual void LeJoueurARemporteLeMatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Le joueur A remporte le match", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
  testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
  testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
  testRunner.Given("Le set est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 59
  testRunner.And("Le set en cours est le set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
  testRunner.And("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table6.AddRow(new string[] {
                            "A",
                            "40",
                            "6",
                            "5",
                            "0"});
                table6.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 61
  testRunner.And("Le score est de :", ((string)(null)), table6, "And ");
#line hidden
#line 65
  testRunner.When("Joueur A marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 66
  testRunner.Then("Le jeu devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table7.AddRow(new string[] {
                            "A",
                            "0",
                            "6",
                            "6",
                            "0"});
                table7.AddRow(new string[] {
                            "B",
                            "0",
                            "0",
                            "0",
                            "0"});
#line 67
  testRunner.And("le score devrait être :", ((string)(null)), table7, "And ");
#line hidden
#line 71
  testRunner.And("Le set devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
  testRunner.And("le resultat du match devrait être \"Jeu, set et match. Victoire du Joueur A : 6-0," +
                        " 6-0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Le joueur B revient à 40-40 et gagne le jeu")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Le joueur B revient à 40-40 et gagne le jeu")]
        public virtual void LeJoueurBRevientA40_40EtGagneLeJeu()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Le joueur B revient à 40-40 et gagne le jeu", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 75
  testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 76
  testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
  testRunner.Given("Le set est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 78
  testRunner.And("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table8.AddRow(new string[] {
                            "A",
                            "40",
                            "5",
                            "0",
                            "0"});
                table8.AddRow(new string[] {
                            "B",
                            "30",
                            "0",
                            "0",
                            "0"});
#line 79
  testRunner.And("Le score est de :", ((string)(null)), table8, "And ");
#line hidden
#line 83
  testRunner.When("Joueur B marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table9.AddRow(new string[] {
                            "A",
                            "40",
                            "5",
                            "0",
                            "0"});
                table9.AddRow(new string[] {
                            "B",
                            "40",
                            "0",
                            "0",
                            "0"});
#line 84
  testRunner.Then("le score devrait être :", ((string)(null)), table9, "Then ");
#line hidden
#line 88
  testRunner.And("Le jeu devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 89
  testRunner.When("Joueur B marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table10.AddRow(new string[] {
                            "A",
                            "40",
                            "5",
                            "0",
                            "0"});
                table10.AddRow(new string[] {
                            "B",
                            "AV",
                            "0",
                            "0",
                            "0"});
#line 90
  testRunner.Then("le score devrait être :", ((string)(null)), table10, "Then ");
#line hidden
#line 94
  testRunner.And("Le jeu devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 95
  testRunner.When("Joueur B marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 96
  testRunner.Then("Le jeu devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table11.AddRow(new string[] {
                            "A",
                            "0",
                            "5",
                            "0",
                            "0"});
                table11.AddRow(new string[] {
                            "B",
                            "0",
                            "1",
                            "0",
                            "0"});
#line 97
  testRunner.And("le score devrait être :", ((string)(null)), table11, "And ");
#line hidden
#line 101
  testRunner.And("le resultat du jeu devrait être \"Le Joueur A mène 5 jeux à 1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Il y a un tie break")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Il y a un tie break")]
        public virtual void IlYAUnTieBreak()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Il y a un tie break", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 103
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 104
  testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 105
  testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 106
  testRunner.Given("Le set est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 107
  testRunner.And("Le set en cours est le set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 108
  testRunner.And("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table12.AddRow(new string[] {
                            "A",
                            "15",
                            "6",
                            "6",
                            "0"});
                table12.AddRow(new string[] {
                            "B",
                            "40",
                            "4",
                            "5",
                            "0"});
#line 109
  testRunner.And("Le score est de :", ((string)(null)), table12, "And ");
#line hidden
#line 113
  testRunner.When("Joueur B marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table13.AddRow(new string[] {
                            "A",
                            "0",
                            "6",
                            "6",
                            "0"});
                table13.AddRow(new string[] {
                            "B",
                            "0",
                            "4",
                            "6",
                            "0"});
#line 114
  testRunner.Then("le score devrait être :", ((string)(null)), table13, "Then ");
#line hidden
#line 118
  testRunner.And("Le jeu devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 119
  testRunner.And("le resultat du jeu devrait être \"6-6 dans le set en cours, tie break\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Joueur A gagne au tie break")]
        [Xunit.TraitAttribute("FeatureTitle", "Tennis")]
        [Xunit.TraitAttribute("Description", "Joueur A gagne au tie break")]
        public virtual void JoueurAGagneAuTieBreak()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Joueur A gagne au tie break", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 122
  testRunner.Given("Le match commence entre A et B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 123
  testRunner.Then("Le match devrait être EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 124
  testRunner.Given("Le set en cours est le set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 125
  testRunner.And("Le jeu est EnCours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 126
  testRunner.And("Le set est TieBreak", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table14.AddRow(new string[] {
                            "A",
                            "6",
                            "2",
                            "6",
                            "0"});
                table14.AddRow(new string[] {
                            "B",
                            "1",
                            "6",
                            "6",
                            "0"});
#line 127
  testRunner.And("Le score est de :", ((string)(null)), table14, "And ");
#line hidden
#line 131
  testRunner.When("Joueur A marque un point", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Joueur",
                            "Score",
                            "Set 1",
                            "Set 2",
                            "Set 3"});
                table15.AddRow(new string[] {
                            "A",
                            "0",
                            "2",
                            "7",
                            "0"});
                table15.AddRow(new string[] {
                            "B",
                            "0",
                            "6",
                            "6",
                            "0"});
#line 132
  testRunner.Then("le score devrait être :", ((string)(null)), table15, "Then ");
#line hidden
#line 136
  testRunner.And("Le jeu devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 137
  testRunner.And("Le set devrait être Terminé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 138
  testRunner.And("Le set en cours devrait être le set 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
  testRunner.And("le resultat du set devrait être \"Le Joueur A remporte le set 7 jeux à 6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TennisFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TennisFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
